### ISSUE TITLE
H

### ISSUE THREAD

**Issue by mightyjsjjsjs** [aioont/kex#2]

**Comment by aioont** [comment]
https://github.com/Hax4us/Nethunter-In-Termux/issues/168#issuecomment-1255470135

I think you followed this and error still exist.The reason is that Android OS kill termux because of PhantomProcessRecord.killLocked().

Please refer to this : 
****https://m.youtube.com/watch?v=jSHpmvfNUUA****


https://github.com/termux/termux-app/issues/2366

https://github.com/RandomCoderOrg/ubuntu-on-android/issues/110


https://youtu.be/tB7b-YCSghQ


This issue is not associated with this program so close it.
Android OS kills the process causing to termination.
I am not a expert at this but try the first YouTube video solution.
I think lower Android version can run termux without problem.

I'm using Android 11 , facing connection failed when I switch or minimize apps.

Ask questions in more active discussion page and someone can help you to fix this problem.

**Comment by aioont** [comment]
What is your issue associated with this program ?

**Comment by SudoRoot75** [comment]
Weak connection
